#!/bin/bash
#!/bin/bash
#Program for voice recognition  task sorting
#Author :Nervewreck
#Rev: 0.1
#Website :Www.thegeekyspace.com



#echo $1
#ps | grep vsort >vsort.pid
case "$1" in
	'ping server')
	cd /home/shark_attack/Programming/bash
	./pi -ping
	;;
	
	'being silver')
	cd /home/shark_attack/Programming/bash
	./pi -ping
	;;
	
	
	
	'remote server')
	cd /home/shark_attack/Programming/bash
	./pi -ssh
	
	;;
	
	'remote sofa')
	cd /home/shark_attack/Programming/bash
	./pi -ssh
	
	;;

	'remote silva')
	cd /home/shark_attack/Programming/bash
	./pi -ssh
	
	;;

	'remote')
	cd /home/shark_attack/Programming/bash
	./pi -ssh
	
	;;


	'remote login')
	cd /home/shark_attack/Programming/bash
	./pi -vnc
	
	;;
	
	'open project')
	 nautilus ~/Videos/PROJECT
	
	;;
	

	
	*)
	echo "Not in selection"
	echo "Please use below selection"
	echo "[remote login]  [ping server]  [open project] [remote server] "
	
        exit 1
	;;
esac
exit 0
